# Generated by Django 5.1.3 on 2024-12-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPack', '0002_carrito_carritoproducto_carrito_productos_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
