# Generated by Django 5.1.3 on 2024-12-01 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPack', '0003_producto_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PartyPack.carrito'),
        ),
    ]
