# Generated by Django 5.1.3 on 2024-12-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PartyPack', '0005_paquete_alter_producto_stock_producto_paquete'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
